/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//
//#define RCC_AHB1ENR   (*(volatile unsigned int *)0x40023830)
//#define GPIOB_MODER   (*(volatile unsigned int *)0x40020400)
//#define GPIOB_BSRR    (*(volatile unsigned int *)0x40020418)
//#define GPIOB_ODR    (*(volatile unsigned int *)0x40020414)
//#define GPIOC_IDR    (*(volatile unsigned int *)0x40020810)
//
//// LED 핀 위치 정의
//#define LD2_PIN 7   // PB7
//
//#define SW1_PIN 13  // PC13

//int main(void) {
//    /* 0. FPU 활성화 (경고 방지 및 안정성) */
//    (*(volatile unsigned int *)0xE000ED88) |= ((3UL << 20) | (3UL << 22));
//
//    /* 1. GPIOB, C 클럭 활성화 */
//    RCC_AHB1ENR |= (3 << 1); // GPIOB, GPIOC 비트 셋
//
//    /* 2. 핀을 출력 모드(01)로 설정 */
//
//    // PB7 설정
//    GPIOB_MODER &= ~(3 << (LD2_PIN * 2));
//    GPIOB_MODER |=  (1 << (LD2_PIN * 2));
//
//    /* 3. BSRR 레지스터를 사용하여 3개 LED 모두 켜기 (High 출력) */
//
//    volatile unsigned int curr,prev = 0;
////
////	while(1){
////		if(GPIOC_IDR & (1 << SW1_PIN)){ //led on
////			GPIOB_BSRR = (1 << LD2_PIN);
////		}
////		else{ //led off
////			GPIOB_BSRR = (1 << LD2_PIN + 16);
////		}
////	};
////
//	while(1){
//		curr = ((GPIOC_IDR >> SW1_PIN) & 1);
//
//			if(curr && (prev == 0)){ //led toggle
//				GPIOB_ODR ^= (1 << LD2_PIN);
//			}
//
//		prev = curr;
//	};
//  //interlock 기법 적용
//}

#include <stdint.h>
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {

	if (LED_init()){
		return 0; //error
	}
	if (SW_init()){
		return 0;
	}

	volatile unsigned int curr,prev = 0;
	volatile unsigned int num = 0;
	int leds[] = {LED_1, LED_2, LED_3};
	while(1){
		curr = SW_ON(); //on or off

		if(curr && (prev == 0)){ // rising edge
			num++;
			num %= 8;
			for (int i = 0; i < 3; i++){
				if((num>>i) & 1){ //led on
					LED_ctrl(leds[i], LEDON);
				}
				else{ //led off
					LED_ctrl(leds[i], LEDOFF);
				}
			}
		}

		prev = curr;
	};

}


/*  int lock = 0;
  while (1)
  {
//      // [1] 딜레이 처리
//      if((GPIOC->IDR>>13) & 0x1){
//          GPIOB->ODR ^= (0x1<<7);        // toggle
//          for(int i=0;i<0x1000000;i++);    // delay=> 이곳에서 멈춰있기 때뭉에 다른작업 정지(bad!)
//      }

      // [2] interlock(flag사용)
      if (lock==0){                        // wait key push(rising edgu)
            if((GPIOC->IDR>>13) & 0x1){    // key push
              GPIOB->ODR ^= (0x1<<7);    // toggle
              lock=1;
          }
      }
      else{                                // wait key release
            if(((GPIOC->IDR>>13) & 0x1)==0){    // key release
              lock=0;
          }
      }

      // [3] interlock(flag사용, 채터링 처리)
      if (lock==0){                        // wait key push(rising edge)
            if((GPIOC->IDR>>13) & 0x1){    // key push
                if (++cnt>1000){            // 1000번연속 같은 값이면 채터링(노이즈) 아님
                  GPIOB->ODR ^= (0x1<<7);    // toggle
                  lock=1;
                }
          }else{
              cnt=0;
          }
      }
      else{                                // wait key release, 필요시 이곳에도 cnt반영
            if(((GPIOC->IDR>>13) & 0x1)==0){    // key release
              lock=0;
          }
      }
      /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  }*/
