/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RCC_AHB1ENR   (*(volatile unsigned int *)0x40023830)
#define GPIOB_MODER   (*(volatile unsigned int *)0x40020400)
#define GPIOB_BSRR    (*(volatile unsigned int *)0x40020418)

// LED 핀 위치 정의
#define LD1_PIN 0   // PB0
#define LD2_PIN 7   // PB7
#define LD3_PIN 14  // PB14
int main(void) {
    /* 0. FPU 활성화 (경고 방지 및 안정성) */
    (*(volatile unsigned int *)0xE000ED88) |= ((3UL << 20) | (3UL << 22));

    /* 1. GPIOB 클럭 활성화 */
    RCC_AHB1ENR |= (1 << 1); // GPIOBEN 비트 셋

    /* 2. 각 핀을 출력 모드(01)로 설정 */
    // PB0 설정
    GPIOB_MODER &= ~(3 << (LD1_PIN * 2));
    GPIOB_MODER |=  (1 << (LD1_PIN * 2));

    // PB7 설정
    GPIOB_MODER &= ~(3 << (LD2_PIN * 2));
    GPIOB_MODER |=  (1 << (LD2_PIN * 2));

    // PB14 설정
    GPIOB_MODER &= ~(3 << (LD3_PIN * 2));
    GPIOB_MODER |=  (1 << (LD3_PIN * 2));

    /* 3. BSRR 레지스터를 사용하여 3개 LED 모두 켜기 (High 출력) */
    // 각 비트 자리에 1을 써주면 해당 핀이 High가 됩니다.
    GPIOB_BSRR = (1 << LD1_PIN) | (1 << LD2_PIN) | (1 << LD3_PIN);

    while (1) {
        // 모든 LED가 켜진 상태 유지
    }
}
